### ISSUE TITLE
Any solution to prevent the bot forgot previous question?

### ISSUE THREAD

**Issue by ahmadkeren** [kuumoneko/edgegpt-js#2]
Any solution to prevent the bot not forgot what i ask before (some modul already use that system)?
My expectation:
Me: "any food suggestion for breakfest?"
Bot: "fried rice"
Me: "why?"
Bot: "Thats good bla bla bla bla"

**Comment by kuumoneko** [comment]
Like chat on bing.com/chat :)?

**Comment by kuumoneko** [comment]
I have tried to use the same Conversation value, but I got the same result from previous.

**Comment by kuumoneko** [comment]
Fixed with commit c549db42aacad51dd9f0db6c4325050eab4fd2b6
