### ISSUE TITLE
User needs to solve CAPTCHA to continue.

### ISSUE THREAD

**Issue by YoiMenn** [kuumoneko/edgegpt-js#3]
when i try to print the response, response give that 🙂

**Comment by kuumoneko** [comment]
You need to go chat in [Bing](https://bing.com/chat) and chat something on there, then get cookie again :)

**Comment by kuumoneko** [comment]
> when i try to print the response, response give that 🙂

You need to go chat in [Bing](https://bing.com/chat) and chat something on there, then get cookie again :)

**Comment by YoiMenn** [comment]
> > when i try to print the response, response give that 🙂
> 
> You need to go chat in [Bing](https://bing.com/chat) and chat something on there, then get cookie again :)

okayy, thanks
