### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by CasandraRos** [kuumoneko/edgegpt-js#5]
resolve(item.item.messages[item.item.messages.length - 1]);
                    ^
TypeError: Cannot read properties of undefined (reading 'length')
    at ChatHub.<anonymous> (file:////node_modules/bingai-js/src/chatbot.js:37:71)
    at Object.onceWrapper (node:events:632:26)
    at ChatHub.emit (node:events:517:28)
    at WebSocket.<anonymous> (file:////node_modules/bingai-js/src/chathub.js:43:34)
    at callListener (//node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (//node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:517:28)
    at Receiver.receiverOnMessage (//node_modules/ws/lib/websocket.js:1209:20)
    at Receiver.emit (node:events:517:28)
    at //node_modules/ws/lib/receiver.js:608:16

**Comment by kuumoneko** [comment]
> resolve(item.item.messages[item.item.messages.length - 1]); ^ TypeError: Cannot read properties of undefined (reading 'length') at ChatHub. (file:////node_modules/bingai-js/src/chatbot.js:37:71) at Object.onceWrapper (node:events:632:26) at ChatHub.emit (node:events:517:28) at WebSocket. (file:////node_modules/bingai-js/src/chathub.js:43:34) at callListener (//node_modules/ws/lib/event-target.js:290:14) at WebSocket.onMessage (//node_modules/ws/lib/event-target.js:209:9) at WebSocket.emit (node:events:517:28) at Receiver.receiverOnMessage (//node_modules/ws/lib/websocket.js:1209:20) at Receiver.emit (node:events:517:28) at //node_modules/ws/lib/receiver.js:608:16

uhm.... i will check this error soon, thanks for your report

**Comment by kuumoneko** [comment]
hmmm... i have tested in my PC, it didn't send me any error.
Have you try using other cookie?

**Comment by CasandraRos** [comment]
I'm using on vps, and there's an error like that. And I have changed the cookie to another one.

**Comment by kuumoneko** [comment]
> I'm using on vps, and there's an error like that. And I have changed the cookie to another one.

Do you use my example code or your code to get a response?

**Comment by CasandraRos** [comment]
> > I'm using on vps, and there's an error like that. And I have changed the cookie to another one.
> 
> Do you use my example code or your code to get a response?

I'm using your code

**Comment by kuumoneko** [comment]
> > > I'm using on vps, and there's an error like that. And I have changed the cookie to another one.
> > 
> > 
> > Do you use my example code or your code to get a response?
> 
> I'm using your code

hmmm... did you try to debug this code. 
Place a breakpoint into line that have error.
Then check does item.item.messages is a list?

**Comment by CasandraRos** [comment]
> > > > I'm using on vps, and there's an error like that. And I have changed the cookie to another one.
> > > 
> > > 
> > > Do you use my example code or your code to get a response?
> > 
> > 
> > I'm using your code
> 
> hmmm... did you try to debug this code. Place a breakpoint into line that have error. Then check does item.item.messages is a list?

I tried to run the code on my pc it worked, but on vps it can't.

**Comment by kuumoneko** [comment]
> > > > > I'm using on vps, and there's an error like that. And I have changed the cookie to another one.
> > > > 
> > > > 
> > > > Do you use my example code or your code to get a response?
> > > 
> > > 
> > > I'm using your code
> > 
> > 
> > hmmm... did you try to debug this code. Place a breakpoint into line that have error. Then check does item.item.messages is a list?
> 
> I tried to run the code on my pc it worked, but on vps it can't.

ohhh... so magic... I will call my friend to check on his VPS

**Comment by kuumoneko** [comment]
what nodejs version did you use in your VPS?

**Comment by CasandraRos** [comment]
> what nodejs version did you use in your VPS?

I am using version 18 for pc and vps
