### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by Rstacx** [kuumoneko/edgegpt-js#6]

**Comment by kuumoneko** [comment]
Hmm... why is it still working on my PC?

**Comment by Rstacx** [comment]
> Hmm... why is it still working on my PC?

not working 😕

**Comment by kuumoneko** [comment]
> > Hmm... why is it still working on my PC?
> 
> not working 😕

can you show all response?

**Comment by Rstacx** [comment]
> > > Hmm... why is it still working on my PC?
> > 
> > 
> > not working 😕
> 
> can you show all response?

`file:///root/ai/node_modules/bingai-js/src/chatbot.js:37
                        resolve(item.item.messages[item.item.messages.length - 1]);
                                                                      ^
TypeError: Cannot read properties of undefined (reading 'length')
    at ChatHub.<anonymous> (file:///root/ai/node_modules/bingai-js/src/chatbot.js:37:71)
    at Object.onceWrapper (node:events:634:26)
    at ChatHub.emit (node:events:519:28)
    at WebSocket.<anonymous> (file:///root/ai/node_modules/bingai-js/src/chathub.js:43:34)
    at callListener (/root/ai/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/root/ai/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:519:28)
    at Receiver.receiverOnMessage (/root/ai/node_modules/ws/lib/websocket.js:1192:20)
    at Receiver.emit (node:events:519:28)
    at Receiver.dataMessage (/root/ai/node_modules/ws/lib/receiver.js:560:14)
Node.js v21.6.1`

**Comment by kuumoneko** [comment]
> > > > Hmm... why is it still working on my PC?
> > > 
> > > 
> > > not working 😕
> > 
> > 
> > can you show all response?
> 
> `file:///root/ai/node_modules/bingai-js/src/chatbot.js:37 resolve(item.item.messages[item.item.messages.length - 1]); ^ TypeError: Cannot read properties of undefined (reading 'length') at ChatHub.<anonymous> (file:///root/ai/node_modules/bingai-js/src/chatbot.js:37:71) at Object.onceWrapper (node:events:634:26) at ChatHub.emit (node:events:519:28) at WebSocket.<anonymous> (file:///root/ai/node_modules/bingai-js/src/chathub.js:43:34) at callListener (/root/ai/node_modules/ws/lib/event-target.js:290:14) at WebSocket.onMessage (/root/ai/node_modules/ws/lib/event-target.js:209:9) at WebSocket.emit (node:events:519:28) at Receiver.receiverOnMessage (/root/ai/node_modules/ws/lib/websocket.js:1192:20) at Receiver.emit (node:events:519:28) at Receiver.dataMessage (/root/ai/node_modules/ws/lib/receiver.js:560:14) Node.js v21.6.1`

did you try to use other cookie?

**Comment by Rstacx** [comment]
> > > > > Hmm... why is it still working on my PC?
> > > > 
> > > > 
> > > > not working 😕
> > > 
> > > 
> > > can you show all response?
> > 
> > 
> > `file:///root/ai/node_modules/bingai-js/src/chatbot.js:37 resolve(item.item.messages[item.item.messages.length - 1]); ^ TypeError: Cannot read properties of undefined (reading 'length') at ChatHub.<anonymous> (file:///root/ai/node_modules/bingai-js/src/chatbot.js:37:71) at Object.onceWrapper (node:events:634:26) at ChatHub.emit (node:events:519:28) at WebSocket.<anonymous> (file:///root/ai/node_modules/bingai-js/src/chathub.js:43:34) at callListener (/root/ai/node_modules/ws/lib/event-target.js:290:14) at WebSocket.onMessage (/root/ai/node_modules/ws/lib/event-target.js:209:9) at WebSocket.emit (node:events:519:28) at Receiver.receiverOnMessage (/root/ai/node_modules/ws/lib/websocket.js:1192:20) at Receiver.emit (node:events:519:28) at Receiver.dataMessage (/root/ai/node_modules/ws/lib/receiver.js:560:14) Node.js v21.6.1`
> 
> did you try to use other cookie?

Yes, but that's how it comes

**Comment by kuumoneko** [comment]
hmmmm

> > > > > > Hmm... why is it still working on my PC?
> > > > > 
> > > > > 
> > > > > not working 😕
> > > > 
> > > > 
> > > > can you show all response?
> > > 
> > > 
> > > `file:///root/ai/node_modules/bingai-js/src/chatbot.js:37 resolve(item.item.messages[item.item.messages.length - 1]); ^ TypeError: Cannot read properties of undefined (reading 'length') at ChatHub.<anonymous> (file:///root/ai/node_modules/bingai-js/src/chatbot.js:37:71) at Object.onceWrapper (node:events:634:26) at ChatHub.emit (node:events:519:28) at WebSocket.<anonymous> (file:///root/ai/node_modules/bingai-js/src/chathub.js:43:34) at callListener (/root/ai/node_modules/ws/lib/event-target.js:290:14) at WebSocket.onMessage (/root/ai/node_modules/ws/lib/event-target.js:209:9) at WebSocket.emit (node:events:519:28) at Receiver.receiverOnMessage (/root/ai/node_modules/ws/lib/websocket.js:1192:20) at Receiver.emit (node:events:519:28) at Receiver.dataMessage (/root/ai/node_modules/ws/lib/receiver.js:560:14) Node.js v21.6.1`
> > 
> > 
> > did you try to use other cookie?
> 
> Yes, but that's how it comes

hmmmm... so hard i have tested for 3 hours but i can't find any bug....

**Comment by Rstacx** [comment]
> hmmmm
> 
> > > > > > > Hmm... why is it still working on my PC?
> > > > > > 
> > > > > > 
> > > > > > not working 😕
> > > > > 
> > > > > 
> > > > > can you show all response?
> > > > 
> > > > 
> > > > `file:///root/ai/node_modules/bingai-js/src/chatbot.js:37 resolve(item.item.messages[item.item.messages.length - 1]); ^ TypeError: Cannot read properties of undefined (reading 'length') at ChatHub.<anonymous> (file:///root/ai/node_modules/bingai-js/src/chatbot.js:37:71) at Object.onceWrapper (node:events:634:26) at ChatHub.emit (node:events:519:28) at WebSocket.<anonymous> (file:///root/ai/node_modules/bingai-js/src/chathub.js:43:34) at callListener (/root/ai/node_modules/ws/lib/event-target.js:290:14) at WebSocket.onMessage (/root/ai/node_modules/ws/lib/event-target.js:209:9) at WebSocket.emit (node:events:519:28) at Receiver.receiverOnMessage (/root/ai/node_modules/ws/lib/websocket.js:1192:20) at Receiver.emit (node:events:519:28) at Receiver.dataMessage (/root/ai/node_modules/ws/lib/receiver.js:560:14) Node.js v21.6.1`
> > > 
> > > 
> > > did you try to use other cookie?
> > 
> > 
> > Yes, but that's how it comes
> 
> hmmmm... so hard i have tested for 3 hours but i can't find any bug....

Are you sure? But I get that error

**Comment by kuumoneko** [comment]
> > hmmmm
> > > > > > > > Hmm... why is it still working on my PC?
> > > > > > > 
> > > > > > > 
> > > > > > > not working 😕
> > > > > > 
> > > > > > 
> > > > > > can you show all response?
> > > > > 
> > > > > 
> > > > > `file:///root/ai/node_modules/bingai-js/src/chatbot.js:37 resolve(item.item.messages[item.item.messages.length - 1]); ^ TypeError: Cannot read properties of undefined (reading 'length') at ChatHub.<anonymous> (file:///root/ai/node_modules/bingai-js/src/chatbot.js:37:71) at Object.onceWrapper (node:events:634:26) at ChatHub.emit (node:events:519:28) at WebSocket.<anonymous> (file:///root/ai/node_modules/bingai-js/src/chathub.js:43:34) at callListener (/root/ai/node_modules/ws/lib/event-target.js:290:14) at WebSocket.onMessage (/root/ai/node_modules/ws/lib/event-target.js:209:9) at WebSocket.emit (node:events:519:28) at Receiver.receiverOnMessage (/root/ai/node_modules/ws/lib/websocket.js:1192:20) at Receiver.emit (node:events:519:28) at Receiver.dataMessage (/root/ai/node_modules/ws/lib/receiver.js:560:14) Node.js v21.6.1`
> > > > 
> > > > 
> > > > did you try to use other cookie?
> > > 
> > > 
> > > Yes, but that's how it comes
> > 
> > 
> > hmmmm... so hard i have tested for 3 hours but i can't find any bug....
> 
> Are you sure? But I get that error

yeah, i can't get any error on my PC... hmmmm,So magic

**Comment by Rstacx** [comment]
> > > hmmmm
> > > > > > > > > Hmm... why is it still working on my PC?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > not working 😕
> > > > > > > 
> > > > > > > 
> > > > > > > can you show all response?
> > > > > > 
> > > > > > 
> > > > > > `file:///root/ai/node_modules/bingai-js/src/chatbot.js:37 resolve(item.item.messages[item.item.messages.length - 1]); ^ TypeError: Cannot read properties of undefined (reading 'length') at ChatHub.<anonymous> (file:///root/ai/node_modules/bingai-js/src/chatbot.js:37:71) at Object.onceWrapper (node:events:634:26) at ChatHub.emit (node:events:519:28) at WebSocket.<anonymous> (file:///root/ai/node_modules/bingai-js/src/chathub.js:43:34) at callListener (/root/ai/node_modules/ws/lib/event-target.js:290:14) at WebSocket.onMessage (/root/ai/node_modules/ws/lib/event-target.js:209:9) at WebSocket.emit (node:events:519:28) at Receiver.receiverOnMessage (/root/ai/node_modules/ws/lib/websocket.js:1192:20) at Receiver.emit (node:events:519:28) at Receiver.dataMessage (/root/ai/node_modules/ws/lib/receiver.js:560:14) Node.js v21.6.1`
> > > > > 
> > > > > 
> > > > > did you try to use other cookie?
> > > > 
> > > > 
> > > > Yes, but that's how it comes
> > > 
> > > 
> > > hmmmm... so hard i have tested for 3 hours but i can't find any bug....
> > 
> > 
> > Are you sure? But I get that error
> 
> yeah, i can't get any error on my PC... hmmmm,So magic

not working 😕 
![Screenshot_20240226_194333_Termius](https://github.com/kuumoneko/edgegpt-js/assets/107676259/6325723a-71ee-4b5f-88ea-8458dff273f4)

**Comment by kuumoneko** [comment]
> > > > hmmmm
> > > > > > > > > > Hmm... why is it still working on my PC?
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > not working 😕
> > > > > > > > 
> > > > > > > > 
> > > > > > > > can you show all response?
> > > > > > > 
> > > > > > > 
> > > > > > > `file:///root/ai/node_modules/bingai-js/src/chatbot.js:37 resolve(item.item.messages[item.item.messages.length - 1]); ^ TypeError: Cannot read properties of undefined (reading 'length') at ChatHub.<anonymous> (file:///root/ai/node_modules/bingai-js/src/chatbot.js:37:71) at Object.onceWrapper (node:events:634:26) at ChatHub.emit (node:events:519:28) at WebSocket.<anonymous> (file:///root/ai/node_modules/bingai-js/src/chathub.js:43:34) at callListener (/root/ai/node_modules/ws/lib/event-target.js:290:14) at WebSocket.onMessage (/root/ai/node_modules/ws/lib/event-target.js:209:9) at WebSocket.emit (node:events:519:28) at Receiver.receiverOnMessage (/root/ai/node_modules/ws/lib/websocket.js:1192:20) at Receiver.emit (node:events:519:28) at Receiver.dataMessage (/root/ai/node_modules/ws/lib/receiver.js:560:14) Node.js v21.6.1`
> > > > > > 
> > > > > > 
> > > > > > did you try to use other cookie?
> > > > > 
> > > > > 
> > > > > Yes, but that's how it comes
> > > > 
> > > > 
> > > > hmmmm... so hard i have tested for 3 hours but i can't find any bug....
> > > 
> > > 
> > > Are you sure? But I get that error
> > 
> > 
> > yeah, i can't get any error on my PC... hmmmm,So magic
> 
> not working 😕 ![Screenshot_20240226_194333_Termius](https://private-user-images.githubusercontent.com/107676259/307822458-6325723a-71ee-4b5f-88ea-8458dff273f4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMTg5NzgsIm5iZiI6MTcwOTAxODY3OCwicGF0aCI6Ii8xMDc2NzYyNTkvMzA3ODIyNDU4LTYzMjU3MjNhLTcxZWUtNGI1Zi04OGVhLTg0NThkZmYyNzNmNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QwNzI0MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDk0YmYzMzk4Yjk0ZTYyMDA1NWE4NTk3ZDZlYzJkOTU3ZDU1ZTIwNmRmZjQzMjQ2MmY5YTE2ODhlMjE0NTY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0z8ngtT636CrTaAfL_K6C6M1qepGSVGOhVAxPy5AVHI)

hmmm... did you try on another node version? Im using node 20.11.0

**Comment by YoiMenn** [comment]
does that happen because bing ai turned into copilot ai?

**Comment by kuumoneko** [comment]
> does that happen because bing ai turned into copilot ai?

erhhh.... but i still using it normally

**Comment by kuumoneko** [comment]
i have tested on another node version and it's okay?

**Comment by YoiMenn** [comment]
yeah, on mine it's work properly, but i  have question, are we have to change the cookie every 30 question / every day? and Is there a limit question to using it?

**Comment by kuumoneko** [comment]
> yeah, on mine it's work properly, but i have question, are we have to change the cookie every 30 question / every day? and Is there a limit question to using it?

hmmmm... I've never used 30 questions per conversation, but just like on Copilot, each cookie can be used for multiple conversations. You can try it. I think we should change cookie every 2-3 days.

**Comment by YoiMenn** [comment]
okay, can i contact you? on discord maybe?

**Comment by kuumoneko** [comment]
> okay, can i contact you? on discord maybe?

ohh, sure, i have used discord, you can find me by *_kuumo* or *kuumo#8026*
