### ISSUE TITLE
这个包不能work

### ISSUE THREAD

**Issue by Tairraos** [kuumoneko/edgegpt-js#7]
readme里的代码应该没有调试过吧，有几处错误，

- test() 写成了 tett()
- const pr = promptSync() 这一行写了两遍。
- readme里的代码依赖 prompt-sync 没提到，最好不要依赖这样的包。直接用简单的字串prompt挺好

解决了上述问题后，npm的包仍然有问题：ultility.cjs:77 的 crypto 没有声明就直接使用了。。。
ReferenceError: crypto is not defined
    at getHeaders (bingai-js@1.7.5-rc6\node_modules\bingai-js\dist\commonjs\ultility.cjs:77:35)

最好找一个干净的机器测试一下代码包。谢谢。

**Comment by kuumoneko** [comment]
thanks : )
